# Generated by Django 6.0.6 on 2026-07-03 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_appointment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='appointment_date',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='appointment',
            old_name='appointment_time',
            new_name='time',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='doctor',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='gender',
        ),
        migrations.AddField(
            model_name='appointment',
            name='reason',
            field=models.TextField(default='Checkup'),
            preserve_default=False,
        ),
    ]
